networks:
   default: 
     driver: bridge 
     name: roboshop 
     #externel: ture # i crated already network docker network create roboshop 
services: 
  mongodb:
     image: subbu2/mongodb:v1 
     container_name: mongodb 
  catalogue: 
     image: subbu2/catalogue:v1 
     container_name:  catalogue 
     depends_on: 
     - mongodb 
  redis:
     image: redis:7.0 
     container_name: redis 
  user: 
     image: subbu2/user:v1 
     container_name: user 
     depends_on: 
     - redis 
     - mongodb 
  cart: 
     image: subbu2/cart:v1 
     container_name: cart 
     depends_on:
     - catalogue 
     - redis 
  mysql:
     image: subbu2/mysql:v1 
     container_name: mysql 
  shipping: 
     image: subbu2/shipping:v1 
     container_name: shipping 
     depends_on: 
     - mysql 
     - cart  